
import os
import math
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import io
import numpy as np
import matplotlib.pyplot as plt
from reportlab.platypus import Image
from Optimizer.Optim_modules.envelope_drag import run_model as compute_drag
from reportlab.lib.units import cm


def _make_drag_chart(airship) -> io.BytesIO:
    airspeeds = np.linspace(0, 20, 200)
    drag_forces = []
    cds = []

    for v in airspeeds:
        result = compute_drag({
            "envelope_radius": float(airship.effective_envelope_radius),
            "airspeed": float(v),
            "cruise_altitude": float(airship.cruise_altitude_m),
        })
        drag_forces.append(result["drag_force_N"])
        cds.append(result["cd"])

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(6, 4), sharex=True)
    fig.suptitle(
        f"Envelope drag  —  R = {airship.effective_envelope_radius:.2f} m, "
        f"altitude = {airship.cruise_altitude_m:.0f} m"
    )
    ax1.plot(airspeeds, drag_forces, color="steelblue")
    ax1.set_ylabel("Drag force [N]")
    ax1.grid(True, linestyle="--", alpha=0.5)

    ax2.plot(airspeeds, cds, color="tomato")
    ax2.set_ylabel("$C_D$ [–]")
    ax2.set_xlabel("Airspeed [m/s]")
    ax2.grid(True, linestyle="--", alpha=0.5)

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return buf


def write_pdf(airship) -> None:
    # Geometry
    r = float(airship.envelope_radius)
    diameter = 2.0 * r
    arm_v = r + float(airship.strut_size)
    arm_h = r + float(airship.effective_strut_size_h)
    z_top = r + 0.5

    wing_area_m2 = math.pi * r ** 2

    it = airship.inertia_tensor
    cog = airship.cog
    empty_mass_kg = float(airship.envelope.weight) + float(airship.solar_panel.weight)
    payload_mass_kg = float(airship.payload.weight)
    battery_mass_kg = float(airship.battery.weight)
    payload_cog = airship.payload.cog
    battery_cog = airship.battery.cog

    dry_gas_mass_kg = float(airship.envelope.gas_mass)
    required_solar_area_m2 = float(airship.solar_panel.req_area)
    num_solar_rings = len(airship.solar_panel._ring_layout)

    keel_z = -(r + float(airship.payload_height) + float(airship.battery_height))

    ballonet_z = -r / 2.0

    here = os.path.dirname(os.path.abspath(__file__))
    kbe_dir = os.path.dirname(here)
    output_dir = os.path.join(kbe_dir)
    os.makedirs(output_dir, exist_ok=True)

    out_path = os.path.join(output_dir, "Airship_Report.pdf")

    doc = SimpleDocTemplate(out_path)
    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(Paragraph("Airship Simulation Report (JSBSim Model)", styles["Title"]))
    story.append(Spacer(1, 12))

    # Mission Analysis
    story.append(Paragraph("Mission Analysis", styles["Heading2"]))
    story.append(Spacer(1, 6))

    ma = airship.mission_analysis

    # Altitude feasibility
    story.append(Paragraph("Altitude Feasibility", styles["Heading3"]))

    feasible = ma.altitude_feasible
    feasible_str = "✔ Feasible" if feasible else "✘ Infeasible"
    margin = ma.altitude_margin_m

    alt_data = [
        ["Target cruise altitude [m]", f"{ma.cruise_altitude_m:.0f}"],
        ["Achievable altitude [m]", f"{ma.achievable_altitude_m:.0f}"],
        ["Altitude margin [m]", f"{margin:+.0f}"],
        ["Feasibility", feasible_str],
    ]

    alt_table = Table(alt_data, colWidths=[10 * cm, 6 * cm])
    alt_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("TEXTCOLOR", (1, 3), (1, 3),
         colors.green if feasible else colors.red),
        ("FONTNAME", (1, 3), (1, 3), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1),
         [colors.whitesmoke, colors.white]),
    ]))
    story.append(alt_table)
    story.append(Spacer(1, 10))

    # Energy & propulsion feasibility
    story.append(Paragraph("Energy & Propulsion Feasibility", styles["Heading3"]))

    ma_energy = airship.mission_analysis

    solar_ok = bool(ma_energy.solar_panels_enough)
    thrust_ok = bool(ma_energy.propeller_thrust_enough)
    energy_gen_kwh = ma_energy.energy_generated_kWh
    energy_con_j = ma_energy.energy_consumed_J
    energy_con_kwh = energy_con_j / 3_600_000

    solar_str = "✔ Sufficient" if solar_ok else "✘ Insufficient"
    thrust_str = "✔ Sufficient" if thrust_ok else "✘ Insufficient"

    energy_data = [
        ["Energy generated by solar panels [kWh]", f"{energy_gen_kwh:.3f}"],
        ["Energy consumed by mission [kWh]", f"{energy_con_kwh:.3f}"],
        ["Solar panels sufficient?", solar_str],
        ["Propeller thrust sufficient?", thrust_str],
    ]

    energy_table = Table(energy_data, colWidths=[10 * cm, 6 * cm])
    energy_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("TEXTCOLOR", (1, 2), (1, 2),
         colors.green if solar_ok else colors.red),
        ("FONTNAME", (1, 2), (1, 2), "Helvetica-Bold"),
        ("TEXTCOLOR", (1, 3), (1, 3),
         colors.green if thrust_ok else colors.red),
        ("FONTNAME", (1, 3), (1, 3), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1),
         [colors.whitesmoke, colors.white]),
    ]))
    story.append(energy_table)
    story.append(Spacer(1, 10))


    # If infeasible, show minimum required radius
    if not feasible:
        from Optimizer.Optim_modules.envelope_buoyancy_module import run_model as compute_buoyancy
        from assembly.mission_analysis import _find_min_radius
        min_r = _find_min_radius(airship, ma.cruise_altitude_m)
        story.append(Paragraph(
            f"<font color='red'><b>Minimum required envelope radius: "
            f"{min_r:.2f} m</b> (all other parameters held constant)</font>",
            styles["Normal"]
        ))
        story.append(Spacer(1, 10))

    # Solar energy generated


    # Geometry section
    story.append(Paragraph("Geometry", styles["Heading2"]))

    geo_data = [
        ["Envelope Radius (m)", f"{r:.3f}"],
        ["Diameter (m)", f"{diameter:.3f}"],
        ["Wing Area (m²)", f"{wing_area_m2:.3f}"],
        ["Horizontal Arm (m)", f"{arm_h:.3f}"],
        ["Vertical Arm (m)", f"{arm_v:.3f}"],
        ["Ballonet Z (m)", f"{ballonet_z:.3f}"],
    ]

    story.append(Table(geo_data))
    story.append(Spacer(1, 12))

    # Drag curve
    story.append(Paragraph("Envelope Drag", styles["Heading2"]))
    story.append(Spacer(1, 6))

    drag_buf = _make_drag_chart(airship)
    story.append(Image(drag_buf, width=440, height=293))  # 6:4 ratio scaled to page
    story.append(Spacer(1, 12))

    story.append(Paragraph("Gas & Solar Panel Info", styles["Heading2"]))

    gas_solar_data = [
        ["Dry Gas Mass (kg)", f"{dry_gas_mass_kg:.3f}"],
        ["Required Solar Area (m²)", f"{required_solar_area_m2:.3f}"],
        ["Number of Solar Panel Rings", f"{num_solar_rings}"],
    ]

    story.append(Table(gas_solar_data))
    story.append(Spacer(1, 12))

    # Mass & inertia

    story.append(Paragraph("Mass & Inertia", styles["Heading2"]))

    mass_data = [
        ["Empty Mass (kg)", f"{empty_mass_kg:.3f}"],
        ["Payload Mass (kg)", f"{payload_mass_kg:.3f}"],
        ["Battery Mass (kg)", f"{battery_mass_kg:.3f}"],
        ["CG (x,y,z)", f"({cog.x:.3f}, {cog.y:.3f}, {cog.z:.3f})"],
        ["Ixx", f"{it['Ixx']:.3f}"],
        ["Iyy", f"{it['Iyy']:.3f}"],
        ["Izz", f"{it['Izz']:.3f}"],
        ["Ixy", f"{it['Ixy']:.6f}"],
        ["Ixz", f"{it['Ixz']:.6f}"],
        ["Iyz", f"{it['Iyz']:.6f}"],
    ]

    story.append(Table(mass_data))
    story.append(Spacer(1, 12))

    # Payload / Bat positions

    story.append(Paragraph("Point Mass Locations", styles["Heading2"]))

    point_data = [
        ["Payload Position", f"({payload_cog.x:.3f}, {payload_cog.y:.3f}, {payload_cog.z:.3f})"],
        ["Battery Position", f"({battery_cog.x:.3f}, {battery_cog.y:.3f}, {battery_cog.z:.3f})"],
        ["Keel Z (ground contact)", f"{keel_z:.3f}"],
    ]

    story.append(Table(point_data))
    story.append(Spacer(1, 12))

    # Propulsion layout summary
    story.append(Paragraph("Propulsion Layout", styles["Heading2"]))

    prop_data = [
        ["Horizontal Port", f"y = -{arm_h:.3f}, yaw control"],
        ["Horizontal Starboard", f"y = +{arm_h:.3f}, yaw control"],
        ["Vertical Fore", f"x = +{arm_v:.3f}, z = {z_top:.3f}"],
        ["Vertical Aft", f"x = -{arm_v:.3f}, z = {z_top:.3f}"],
        ["Vertical Port", f"y = -{arm_v:.3f}, z = {z_top:.3f}"],
        ["Vertical Starboard", f"y = +{arm_v:.3f}, z = {z_top:.3f}"],
    ]

    story.append(Table(prop_data))
    story.append(Spacer(1, 12))

    doc.build(story)

    print(f"[write_pdf] Written → {out_path}")